const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const source=fs.readFileSync(require.resolve('../public/app.js'),'utf8');const ctx=vm.createContext({escapeHtml:v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))});
vm.runInContext(source.slice(source.indexOf('function renderIntentBlocks('),source.indexOf('function renderLineNumbers(')),ctx);
const steps=[{type:'GIVEN',text:'A button labeled "Save"'},{type:'WHEN',text:'click the button'},{type:'THEN',text:'show a toast with content "Saved"'}];
test('inserting AND preserves all existing values and order',()=>{const before=JSON.stringify(steps);const inserted=ctx.insertIntentAnd(steps,0);assert.equal(JSON.stringify(steps),before);assert.deepEqual(Array.from(inserted,s=>s.type),['GIVEN','AND','WHEN','THEN']);assert.equal(inserted[2].text,steps[1].text);});
test('AND inherits component or outcome suggestions from its preceding block',()=>{let html=ctx.renderIntentBlocks(ctx.insertIntentAnd(steps,0));assert.match(html,/data-intent-type="AND" data-suggestion-context="GIVEN"/);html=ctx.renderIntentBlocks(ctx.insertIntentAnd(steps,2));assert.match(html,/data-intent-type="AND" data-suggestion-context="THEN"/);});
test('adding AND after THEN executes both results',()=>{const preview=require('../public/component-preview.js');const inserted=ctx.insertIntentAnd(steps,2);inserted[3].text='update the button label to "Done"';const s=preview.analyze({steps:inserted});assert.equal(s.interactions.length,2);assert.equal(s.interactions[1].action,'text');});

test('AND rows belong to three primary groups with one add control per eligible group',()=>{const input=ctx.insertIntentAnd(ctx.insertIntentAnd(steps,0),1);const html=ctx.renderIntentBlocks(input);assert.equal((html.match(/data-intent-group=/g)||[]).length,3);assert.equal((html.match(/data-action="add-intent-and"/g)||[]).length,2);assert.match(html,/data-after-index="2"[^>]*>\+ AND · Component/);assert.match(html,/Additional component/);});
test('empty AND is removable without deleting populated rows or changing current input',()=>{const input=ctx.insertIntentAnd(steps,0);input[0].text='A button with my latest edit';const output=ctx.removeEmptyIntentAnd(input,1);assert.equal(output.length,3);assert.equal(output[0].text,input[0].text);input[1].text='A required input';assert.equal(ctx.removeEmptyIntentAnd(input,1),input);assert.equal(ctx.removeEmptyIntentAnd(input,0),input);});
test('only empty AND exposes a remove action',()=>{const input=ctx.insertIntentAnd(steps,2);assert.match(ctx.renderIntentBlocks(input),/data-action="remove-intent-and"/);input[3].text='show a toast';assert.doesNotMatch(ctx.renderIntentBlocks(input),/data-action="remove-intent-and"/);assert.match(ctx.renderIntentBlocks(input),/Additional outcome/);});
