'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const api = require('../public/component-preview.js');
function generated(given, when = '', then = '', intent = 'Omnichannel campaign') {
  return {intent, entities: [], valid: Boolean(given && when && then), steps: [
    {type:'GIVEN',text:given},{type:'WHEN',text:when},{type:'THEN',text:then}
  ]};
}
for (const entry of Object.values(api.registry)) {
  test(`${entry.type}: standalone, all four systems, correct JSON and no workflow wrapper`, () => {
    const spec = api.analyze(generated('a ' + entry.aliases[0]));
    assert.equal(spec.componentCount, 1);
    assert.equal(spec.components[0].type, entry.type);
    assert.equal(spec.valid, true);
    for (const system of ['dls','ant','material','connected']) {
      const html = api.render(spec, system);
      assert.equal((html.match(/data-component=/g) || []).length, 1);
      assert.match(html, new RegExp(`data-component="${entry.type}"`));
      assert.doesNotMatch(html, /prototype-window|prototype-card|Create omnichannel|Eligibility requirements|Save draft|8\.7|Generated by DLS/);
      const output = api.output(spec, system);
      assert.deepEqual(output.designSystem.components, [entry.bindings[system]]);
      assert.equal(output.components[0].binding, entry.bindings[system]);
    }
  });
  for (const alias of entry.aliases) test(`alias ${alias}`, () => {
    const spec = api.analyze(generated('a ' + alias));
    assert.equal(spec.componentCount,1);
    assert.equal(spec.components[0].type,entry.type);
  });
}
for (const [prompt, expected] of [
  ['a button and a checkbox', ['Button','Checkbox']],
  ['an email input and a primary button labeled "Submit"', ['Input','Button']],
  ['a card with an input labeled "Email" and a button labeled "Save"', ['Card','Input','Button']],
  ['a checkbox and a button inside a card', ['Card','Checkbox','Button']],
  ['a dialog containing a form with an input and a button', ['Dialog','Form','Input','Button']],
  ['two buttons', ['Button','Button']],
  ['3 cards', ['Card','Card','Card']],
  ['a button that opens a dialog', ['Button']],
  ['a button without a card', ['Button']],
  ['a button with text "Save"', ['Button']],
  ['a button labeled "Open dialog"', ['Button']],
  ['a card with title "Settings"', ['Card']],
  ['a radio button', ['Radio']],
  ['a date input', ['DatePicker']]
]) test(`composition: ${prompt}`, () => {
  const spec = api.analyze(generated(prompt));
  assert.deepEqual(api.flat(spec.components).map(c => c.type),expected);
  assert.equal(spec.componentCount,expected.length);
});
test('exact screenshot placeholders do not become UI copy', () => {
  const spec=api.analyze(generated('a button','Describe the triggering condition.','Describe the expected outcome.'));
  assert.equal(spec.valid,true);
  assert.equal(spec.steps[1].text,'');
  assert.equal(spec.steps[2].text,'');
  assert.doesNotMatch(api.render(spec),/Describe|campaign/i);
});
test('missing WHEN/THEN allowed for every static component; project title never supplies content', () => {
  const a=api.analyze(generated('a checkbox','','','Omnichannel'));
  const b=api.analyze(generated('a checkbox','','','Checkout form'));
  assert.deepEqual(a.components,b.components);
});
test('container composition does not wrap siblings twice',()=>{
  const spec=api.analyze(generated('a card with an input and a button'));
  assert.equal(spec.components.length,1);
  assert.deepEqual(spec.components[0].children.map(c=>c.type),['Input','Button']);
});
test('individual component labels and disabled state do not bleed into siblings',()=>{
  const spec=api.analyze(generated('a disabled checkbox labeled "Accept" and a button labeled "Save"'));
  assert.equal(spec.components[0].props.label,'Accept');
  assert.equal(spec.components[0].props.disabled,true);
  assert.equal(spec.components[1].props.label,'Save');
  assert.equal(spec.components[1].props.disabled,false);
});
for (const [prompt,key,value] of [
  ['a button labeled "Save"','label','Save'],
  ["a 'Delete' button",'label','Delete'],
  ['a Save button','label','Save'],
  ['a button labeled Submit','label','Submit'],
  ['a secondary button','variant','secondary'],
  ['a disabled input','disabled',true],
  ['an unchecked checkbox','checked',false],
  ['a checked checkbox','checked',true],
  ['a switch that is not disabled','disabled',false],
  ['an input with placeholder "Your email"','placeholder','Your email'],
  ['a progress bar at 65%','numericValue',65],
  ['a slider min 10 max 50 value 30','numericValue',30],
  ['an input labeled "Disabled"','disabled',false],
  ['an email input','inputType','email']
]) test(`props: ${prompt}`,()=>assert.equal(api.analyze(generated(prompt)).components[0].props[key],value));
for (const [prompt, expected] of [
 ['a dropdown with options "Small", "Medium", "Large"',['Small','Medium','Large']],
 ['a dropdown with options "Small, Medium, Large"',['Small','Medium','Large']],
 ['tabs with labels "Overview", "Settings"',['Overview','Settings']],
 ['a table with columns "Name", "Status"',['Name','Status']],
 ['a list with items One, Two, Three',['One','Two','Three']]
]) test(`options: ${prompt}`,()=>assert.deepEqual(api.analyze(generated(prompt)).components[0].props.options,expected));
test('unknown component never becomes a workflow',()=>{
 const spec=api.analyze(generated('a carousel','user swipes','show next image'));
 assert.equal(spec.valid,false); assert.equal(spec.componentCount,0);
 assert.match(api.render(spec),/Not rendered/); assert.doesNotMatch(api.render(spec),/prototype-window/);
});
test('unsupported member of a composition is visible, not silently ignored',()=>{
 const spec=api.analyze(generated('a button and a chart'));
 assert.equal(spec.valid,false); assert.match(spec.warnings.join(),/chart/);
});
test('full workflow with no component specification retains legacy path',()=>{
 const spec=api.analyze(generated('an advertiser setting up a campaign','data is ready','create a campaign'));
 assert.equal(spec.previewEngine,undefined); assert.equal(spec.valid,true);
});
test('workflow placeholder descriptions are not valid behavior',()=>{
 const spec=api.analyze(generated('an advertiser','Describe the triggering condition.','Describe the expected outcome.'));
 assert.equal(spec.valid,false);
});
test('an explicit AND component is added; future effects are not',()=>{
 const input=generated('a button','clicked','show a modal');
 input.steps.push({type:'AND',text:'a checkbox'});
 assert.equal(api.analyze(input).componentCount,2);
});
test('enrichment is idempotent and does not mutate saved input',()=>{
 const input=generated('a card');const old=JSON.stringify(input);const a=api.analyze(input);
 assert.strictEqual(api.analyze(a),a);assert.equal(JSON.stringify(input),old);
});
test('sample data and actions are never invented in tables, cards or forms',()=>{
 for(const type of ['table','card','form']){
  const html=api.render(generated('a '+type));
  assert.doesNotMatch(html,/<button|Ready|Validated|8\.7|Save draft|Purchase|Revenue/);
 }
});
test('count cap is explicit and bounded',()=>{
 const spec=api.analyze(generated('100 buttons')); assert.equal(spec.componentCount,20);
 assert.match(spec.warnings.join(),/20/);assert.equal(spec.valid,false);
});
test('HTML injection escaped in labels, contents and options',()=>{
 for(const type of ['button','input','alert','card']){
  const html=api.render(generated(`a ${type} labeled "<img src=x onerror=alert(1)>"`));
  assert.doesNotMatch(html,/<img src=x/);assert.match(html,/&lt;img/);
 }
});
for(const bad of ['javascript:alert(1)','data:image/svg+xml,<svg/>','//evil.test/x','vbscript:bad']){
 test(`unsafe URL ${bad}`,()=>assert.equal(api.safeUrl(bad),''));
}
test('expanded and inline previews have unique IDs',()=>{
 const a=api.render(generated('tabs with labels "One", "Two"'),'ant');
 const b=api.render(generated('tabs with labels "One", "Two"'),'ant',true);
 const idsA=[...a.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
 const idsB=[...b.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
 assert.equal(new Set([...idsA,...idsB]).size,idsA.length+idsB.length);
});
