'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const api = require('../public/standalone-button-preview.js');
const generated = (given, when = '', then = '', intent = 'Omnichannel campaign') => ({
  intent, entities: [], valid: Boolean(given && when && then),
  steps: [{type: 'GIVEN', text: given}, {type: 'WHEN', text: when}, {type: 'THEN', text: then}]
});
for (const input of ['a button', 'A BUTTON', 'a primary button', 'a simple round button', 'show me a button', 'a button, not a card', 'a button without a card', 'a button that opens a modal', 'a button with an icon', 'a button with 2 px border', 'a button with 12 px padding', 'a button with 100 px width']) {
  test(`standalone: ${input}`, () => assert.ok(api.buttonSpec(generated(input))));
}
for (const input of ['', 'a card', 'a form with a submit button', 'a page containing a button', 'a button inside a card', 'a button and a text input', 'two buttons', '2 button', 'a button group with two actions', 'an omnichannel campaign dashboard']) {
  test(`not a standalone button: ${input}`, () => assert.equal(api.buttonSpec(generated(input)), null));
}
for (const [input, label] of [['a button labeled "Save"', 'Save'], ['a button with text “Publish”', 'Publish'], ["a 'Delete' button", 'Delete'], ['a Save button', 'Save'], ['a button labeled Submit', 'Submit'], ['a primary button', 'Button']]) {
  test(`label: ${input}`, () => assert.equal(api.buttonSpec(generated(input)).label, label));
}
test('screenshot regression: project title and placeholder outcomes do not supply UI', () => {
  const parsed = api.enrich(generated('a button', 'Describe the triggering condition.', 'Describe the expected outcome.'));
  assert.equal(parsed.valid, true);
  assert.equal(parsed.scope, 'component');
  assert.equal(parsed.components.length, 1);
  assert.equal(parsed.steps[1].text, '');
  assert.equal(parsed.steps[2].text, '');
  const html = api.renderButton(parsed.components[0].props, 'ant');
  assert.equal((html.match(/<button\b/g) || []).length, 1);
  assert.match(html, />Button<\/button>/);
  assert.match(html, /ds-ant/);
  assert.doesNotMatch(html, /campaign|Eligibility|Save draft|8\.7|class="prototype-window|class="prototype-card|Describe|run-prototype|Generated by/i);
});
test('static button works with GIVEN only', () => assert.equal(api.enrich(generated('a button')).valid, true));
test('full workflows pass through unchanged', () => {
  const input = generated('an advertiser setting up a campaign', 'data is ready', 'create the campaign');
  assert.strictEqual(api.enrich(input), input);
});
test('explicit disabled and secondary variants', () => {
  const spec = api.buttonSpec(generated('a disabled secondary button labeled "Save"'));
  const html = api.renderButton(spec);
  assert.equal(spec.disabled, true);
  assert.equal(spec.variant, 'secondary');
  assert.match(html, / disabled/);
  assert.match(html, /prototype-secondary/);
});
test('not disabled stays enabled', () => assert.equal(api.buttonSpec(generated('a button that is not disabled')).disabled, false));
test('user labels are escaped, never executable HTML', () => {
  const html = api.renderButton({ label: '<img src=x onerror=alert(1)>', variant: 'primary', disabled: false });
  assert.doesNotMatch(html, /<img/);
  assert.match(html, /&lt;img/);
});
test('outcome text is not used as the initial label', () => {
  assert.equal(api.buttonSpec(generated('a button labeled "Save"', 'it is clicked', 'the label changes to "Saved"')).label, 'Save');
});
test('expanded preview stays component-only and retains selected system', () => {
  const html = api.renderButton({label: 'Save'}, 'material', true);
  assert.match(html, /ds-material/);
  assert.match(html, /prototype-stage-expanded/);
  assert.equal((html.match(/<button\b/g) || []).length, 1);
});
test('browser adapter updates parser, renderer, summary, and preserves workflow fallback', () => {
  const summary = {textContent: ''};
  const subtitle = {textContent: ''};
  const tasks = [];
  const ctx = vm.createContext({
    console, queueMicrotask: fn => tasks.push(fn),
    document: {querySelector: () => summary, getElementById: id => id === 'preview-description' ? subtitle : null}
  });
  vm.runInContext(`
    const state = {activeProject: {name: 'Omnichannel campaign'}, editorText: 'a button', designSystem: 'ant'};
    const DESIGN_SYSTEMS = {ant: {name: 'Ant Design'}};
    function designSystemComponents() { return Array(6); }
    function parseStructuredLanguage(text, name) { return { intent:name, steps:[{type:'GIVEN',text}], valid:false }; }
    function renderGeneratedInterface() { return '<section>legacy workflow</section>'; }
    function renderOutput(generated) { return renderGeneratedInterface(generated); }
    function renderPreviewModal() { return renderOutput(parseStructuredLanguage(state.editorText)); }
  `, ctx);
  vm.runInContext(fs.readFileSync(require.resolve('../public/standalone-button-preview.js'), 'utf8'), ctx);
  assert.match(vm.runInContext('renderOutput(parseStructuredLanguage(state.editorText))', ctx), /data-component="Button"/);
  while (tasks.length) tasks.shift()();
  assert.equal(summary.textContent, 'Ant Design · 1 component');
  assert.equal(subtitle.textContent, '1 component · Ant Design');
  vm.runInContext("state.editorText = 'a form with a button'; renderOutput(parseStructuredLanguage(state.editorText));", ctx);
  while (tasks.length) tasks.shift()();
  assert.equal(summary.textContent, 'Ant Design · 6 components');
  assert.equal(vm.runInContext('renderOutput(parseStructuredLanguage(state.editorText))', ctx), '<section>legacy workflow</section>');
  const before = ctx.parseStructuredLanguage;
  ctx.DLSButtonPreview.install(ctx);
  assert.strictEqual(ctx.parseStructuredLanguage, before);
});
