// Generated by scripts/generate_theme.py. Edit DesignSystem/tokens.json, then regenerate.
// Canonical token SHA-256: c6c25f546c5a2f01271f32e91d356c0103c695e8b9ed4ef41038508d3471f5b2
// Source CSS SHA-256: 68c58a97d7adf59af11cb54457fb7257a9a1ca360b24f86f966cff08276bd5f4
import SwiftUI
import UIKit

enum DLSTheme {
    // background: dark #08080a; light #f5f5f3
    static let background = Color(uiColor: UIColor { traits in
        traits.userInterfaceStyle == .dark ? UIColor(red: 8.0 / 255, green: 8.0 / 255, blue: 10.0 / 255, alpha: 1) : UIColor(red: 245.0 / 255, green: 245.0 / 255, blue: 243.0 / 255, alpha: 1)
    })
    // surface: dark #111114; light #ffffff
    static let surface = Color(uiColor: UIColor { traits in
        traits.userInterfaceStyle == .dark ? UIColor(red: 17.0 / 255, green: 17.0 / 255, blue: 20.0 / 255, alpha: 1) : UIColor(red: 255.0 / 255, green: 255.0 / 255, blue: 255.0 / 255, alpha: 1)
    })
    // surface2: dark #151519; light #f7f7f5
    static let surface2 = Color(uiColor: UIColor { traits in
        traits.userInterfaceStyle == .dark ? UIColor(red: 21.0 / 255, green: 21.0 / 255, blue: 25.0 / 255, alpha: 1) : UIColor(red: 247.0 / 255, green: 247.0 / 255, blue: 245.0 / 255, alpha: 1)
    })
    // surface3: dark #1a1a1f; light #efefec
    static let surface3 = Color(uiColor: UIColor { traits in
        traits.userInterfaceStyle == .dark ? UIColor(red: 26.0 / 255, green: 26.0 / 255, blue: 31.0 / 255, alpha: 1) : UIColor(red: 239.0 / 255, green: 239.0 / 255, blue: 236.0 / 255, alpha: 1)
    })
    // text: dark #f4f2ef; light #1d1d20
    static let text = Color(uiColor: UIColor { traits in
        traits.userInterfaceStyle == .dark ? UIColor(red: 244.0 / 255, green: 242.0 / 255, blue: 239.0 / 255, alpha: 1) : UIColor(red: 29.0 / 255, green: 29.0 / 255, blue: 32.0 / 255, alpha: 1)
    })
    // textSoft: dark #c2c0c4; light #4e4e55
    static let soft = Color(uiColor: UIColor { traits in
        traits.userInterfaceStyle == .dark ? UIColor(red: 194.0 / 255, green: 192.0 / 255, blue: 196.0 / 255, alpha: 1) : UIColor(red: 78.0 / 255, green: 78.0 / 255, blue: 85.0 / 255, alpha: 1)
    })
    // muted: dark #86858d; light #686870
    static let muted = Color(uiColor: UIColor { traits in
        traits.userInterfaceStyle == .dark ? UIColor(red: 134.0 / 255, green: 133.0 / 255, blue: 141.0 / 255, alpha: 1) : UIColor(red: 104.0 / 255, green: 104.0 / 255, blue: 112.0 / 255, alpha: 1)
    })
    // line: dark rgba(255,255,255,0.09); light rgba(24,24,27,0.11)
    static let border = Color(uiColor: UIColor { traits in
        traits.userInterfaceStyle == .dark ? UIColor(red: 255.0 / 255, green: 255.0 / 255, blue: 255.0 / 255, alpha: 0.09) : UIColor(red: 24.0 / 255, green: 24.0 / 255, blue: 27.0 / 255, alpha: 0.11)
    })
    // lineStrong: dark rgba(255,255,255,0.16); light rgba(24,24,27,0.20)
    static let strongBorder = Color(uiColor: UIColor { traits in
        traits.userInterfaceStyle == .dark ? UIColor(red: 255.0 / 255, green: 255.0 / 255, blue: 255.0 / 255, alpha: 0.16) : UIColor(red: 24.0 / 255, green: 24.0 / 255, blue: 27.0 / 255, alpha: 0.2)
    })
    // gold: dark #c7a86b; light #c7a86b
    static let gold = Color(uiColor: UIColor { traits in
        traits.userInterfaceStyle == .dark ? UIColor(red: 199.0 / 255, green: 168.0 / 255, blue: 107.0 / 255, alpha: 1) : UIColor(red: 199.0 / 255, green: 168.0 / 255, blue: 107.0 / 255, alpha: 1)
    })
    // primaryFill: dark #f2f1f4; light #f2f1f4
    static let primaryFill = Color(uiColor: UIColor { traits in
        traits.userInterfaceStyle == .dark ? UIColor(red: 242.0 / 255, green: 241.0 / 255, blue: 244.0 / 255, alpha: 1) : UIColor(red: 242.0 / 255, green: 241.0 / 255, blue: 244.0 / 255, alpha: 1)
    })
    // primaryInk: dark #151519; light #151519
    static let primaryInk = Color(uiColor: UIColor { traits in
        traits.userInterfaceStyle == .dark ? UIColor(red: 21.0 / 255, green: 21.0 / 255, blue: 25.0 / 255, alpha: 1) : UIColor(red: 21.0 / 255, green: 21.0 / 255, blue: 25.0 / 255, alpha: 1)
    })
    // violet: dark #8b78ff; light #8b78ff
    static let violet = Color(uiColor: UIColor { traits in
        traits.userInterfaceStyle == .dark ? UIColor(red: 139.0 / 255, green: 120.0 / 255, blue: 255.0 / 255, alpha: 1) : UIColor(red: 139.0 / 255, green: 120.0 / 255, blue: 255.0 / 255, alpha: 1)
    })
    // green: dark #62d59b; light #62d59b
    static let green = Color(uiColor: UIColor { traits in
        traits.userInterfaceStyle == .dark ? UIColor(red: 98.0 / 255, green: 213.0 / 255, blue: 155.0 / 255, alpha: 1) : UIColor(red: 98.0 / 255, green: 213.0 / 255, blue: 155.0 / 255, alpha: 1)
    })
    // blue: dark #6ca7ff; light #6ca7ff
    static let blue = Color(uiColor: UIColor { traits in
        traits.userInterfaceStyle == .dark ? UIColor(red: 108.0 / 255, green: 167.0 / 255, blue: 255.0 / 255, alpha: 1) : UIColor(red: 108.0 / 255, green: 167.0 / 255, blue: 255.0 / 255, alpha: 1)
    })
    // amber: dark #e7b764; light #e7b764
    static let amber = Color(uiColor: UIColor { traits in
        traits.userInterfaceStyle == .dark ? UIColor(red: 231.0 / 255, green: 183.0 / 255, blue: 100.0 / 255, alpha: 1) : UIColor(red: 231.0 / 255, green: 183.0 / 255, blue: 100.0 / 255, alpha: 1)
    })
    // pink: dark #ef8ab8; light #ef8ab8
    static let pink = Color(uiColor: UIColor { traits in
        traits.userInterfaceStyle == .dark ? UIColor(red: 239.0 / 255, green: 138.0 / 255, blue: 184.0 / 255, alpha: 1) : UIColor(red: 239.0 / 255, green: 138.0 / 255, blue: 184.0 / 255, alpha: 1)
    })
    // cyan: dark #58cfda; light #58cfda
    static let cyan = Color(uiColor: UIColor { traits in
        traits.userInterfaceStyle == .dark ? UIColor(red: 88.0 / 255, green: 207.0 / 255, blue: 218.0 / 255, alpha: 1) : UIColor(red: 88.0 / 255, green: 207.0 / 255, blue: 218.0 / 255, alpha: 1)
    })
    // danger: dark #f18484; light #f18484
    static let danger = Color(uiColor: UIColor { traits in
        traits.userInterfaceStyle == .dark ? UIColor(red: 241.0 / 255, green: 132.0 / 255, blue: 132.0 / 255, alpha: 1) : UIColor(red: 241.0 / 255, green: 132.0 / 255, blue: 132.0 / 255, alpha: 1)
    })
    // Explicit native input visibility adaptation; decorative borders retain web alpha.
    static let editableOutline = Color(uiColor: UIColor { traits in
        traits.userInterfaceStyle == .dark ? UIColor(red: 119.0 / 255, green: 119.0 / 255, blue: 128.0 / 255, alpha: 1) : UIColor(red: 137.0 / 255, green: 137.0 / 255, blue: 144.0 / 255, alpha: 1)
    })
    // CSS background arrays are top layer first; DLSGradientSurface reverses painting order.
    enum GradientRole: CaseIterable { case authBackground, authCard, dashboardHero, projectCard, goldButton, goldButtonHover, authBackgroundMobile }
    static func gradientLayers(_ role: GradientRole, scheme: ColorScheme, width: CGFloat) -> [DLSGradientLayer] {
        switch role {
        case .authBackground:
            // Source @media (max-width: 760px); later light-theme override is retained.
            if width <= 760 { return gradientLayers(.authBackgroundMobile, scheme: scheme, width: width) }
            if scheme == .dark {
                return [.radial(center: UnitPoint(x: 0.1, y: 0.05), stops: [.init(color: Color(uiColor: UIColor(red: 255.0 / 255, green: 255.0 / 255, blue: 255.0 / 255, alpha: 0.06)), location: 0), .init(color: Color.clear, location: 0.32)]), .linear(degrees: 125, stops: [.init(color: Color(uiColor: UIColor(red: 18.0 / 255, green: 18.0 / 255, blue: 22.0 / 255, alpha: 1)), location: 0), .init(color: Color(uiColor: UIColor(red: 8.0 / 255, green: 8.0 / 255, blue: 10.0 / 255, alpha: 1)), location: 0.62), .init(color: Color(uiColor: UIColor(red: 5.0 / 255, green: 5.0 / 255, blue: 6.0 / 255, alpha: 1)), location: 1)])]
            }
            return [.radial(center: UnitPoint(x: 0.1, y: 0.05), stops: [.init(color: Color(uiColor: UIColor(red: 255.0 / 255, green: 255.0 / 255, blue: 255.0 / 255, alpha: 0.9)), location: 0), .init(color: Color.clear, location: 0.34)]), .linear(degrees: 125, stops: [.init(color: Color(uiColor: UIColor(red: 232.0 / 255, green: 232.0 / 255, blue: 229.0 / 255, alpha: 1)), location: 0), .init(color: Color(uiColor: UIColor(red: 245.0 / 255, green: 245.0 / 255, blue: 242.0 / 255, alpha: 1)), location: 0.62), .init(color: Color(uiColor: UIColor(red: 255.0 / 255, green: 255.0 / 255, blue: 255.0 / 255, alpha: 1)), location: 1)])]
        case .authCard:
            if scheme == .dark {
                return [.linear(degrees: 145, stops: [.init(color: Color(uiColor: UIColor(red: 25.0 / 255, green: 25.0 / 255, blue: 29.0 / 255, alpha: 0.92)), location: 0), .init(color: Color(uiColor: UIColor(red: 13.0 / 255, green: 13.0 / 255, blue: 16.0 / 255, alpha: 0.94)), location: 1)])]
            }
            return [.solid(Color(uiColor: UIColor(red: 255.0 / 255, green: 255.0 / 255, blue: 255.0 / 255, alpha: 0.88)))]
        case .dashboardHero:
            if scheme == .dark {
                return [.radial(center: UnitPoint(x: 0.85, y: 0.35), stops: [.init(color: Color(uiColor: UIColor(red: 255.0 / 255, green: 255.0 / 255, blue: 255.0 / 255, alpha: 0.11)), location: 0), .init(color: Color.clear, location: 0.12)]), .linear(degrees: 120, stops: [.init(color: Color(uiColor: UIColor(red: 255.0 / 255, green: 255.0 / 255, blue: 255.0 / 255, alpha: 0.04)), location: 0), .init(color: Color(uiColor: UIColor(red: 255.0 / 255, green: 255.0 / 255, blue: 255.0 / 255, alpha: 0.008)), location: 1)])]
            }
            return [.radial(center: UnitPoint(x: 0.8, y: 0.1), stops: [.init(color: Color(uiColor: UIColor(red: 111.0 / 255, green: 86.0 / 255, blue: 229.0 / 255, alpha: 0.13)), location: 0), .init(color: Color.clear, location: 0.34)]), .linear(degrees: 135, stops: [.init(color: Color(uiColor: UIColor(red: 255.0 / 255, green: 255.0 / 255, blue: 255.0 / 255, alpha: 1)), location: 0), .init(color: Color(uiColor: UIColor(red: 239.0 / 255, green: 239.0 / 255, blue: 236.0 / 255, alpha: 1)), location: 1)])]
        case .projectCard:
            if scheme == .dark {
                return [.linear(degrees: 145, stops: [.init(color: Color(uiColor: UIColor(red: 255.0 / 255, green: 255.0 / 255, blue: 255.0 / 255, alpha: 0.035)), location: 0), .init(color: Color(uiColor: UIColor(red: 255.0 / 255, green: 255.0 / 255, blue: 255.0 / 255, alpha: 0.012)), location: 1)])]
            }
            return [.solid(Color(uiColor: UIColor(red: 255.0 / 255, green: 255.0 / 255, blue: 255.0 / 255, alpha: 1)))]
        case .goldButton:
            if scheme == .dark {
                return [.linear(degrees: 180, stops: [.init(color: Color(uiColor: UIColor(red: 217.0 / 255, green: 189.0 / 255, blue: 128.0 / 255, alpha: 1)), location: 0), .init(color: Color(uiColor: UIColor(red: 185.0 / 255, green: 147.0 / 255, blue: 82.0 / 255, alpha: 1)), location: 1)])]
            }
            return [.linear(degrees: 180, stops: [.init(color: Color(uiColor: UIColor(red: 217.0 / 255, green: 189.0 / 255, blue: 128.0 / 255, alpha: 1)), location: 0), .init(color: Color(uiColor: UIColor(red: 185.0 / 255, green: 147.0 / 255, blue: 82.0 / 255, alpha: 1)), location: 1)])]
        case .goldButtonHover:
            if scheme == .dark {
                return [.linear(degrees: 180, stops: [.init(color: Color(uiColor: UIColor(red: 227.0 / 255, green: 202.0 / 255, blue: 144.0 / 255, alpha: 1)), location: 0), .init(color: Color(uiColor: UIColor(red: 197.0 / 255, green: 160.0 / 255, blue: 95.0 / 255, alpha: 1)), location: 1)])]
            }
            return [.linear(degrees: 180, stops: [.init(color: Color(uiColor: UIColor(red: 227.0 / 255, green: 202.0 / 255, blue: 144.0 / 255, alpha: 1)), location: 0), .init(color: Color(uiColor: UIColor(red: 197.0 / 255, green: 160.0 / 255, blue: 95.0 / 255, alpha: 1)), location: 1)])]
        case .authBackgroundMobile:
            if scheme == .dark {
                return [.radial(center: UnitPoint(x: 0.5, y: 0.02), stops: [.init(color: Color(uiColor: UIColor(red: 139.0 / 255, green: 120.0 / 255, blue: 255.0 / 255, alpha: 0.11)), location: 0), .init(color: Color.clear, location: 0.35)]), .solid(Color(uiColor: UIColor(red: 8.0 / 255, green: 8.0 / 255, blue: 10.0 / 255, alpha: 1)))]
            }
            return [.radial(center: UnitPoint(x: 0.1, y: 0.05), stops: [.init(color: Color(uiColor: UIColor(red: 255.0 / 255, green: 255.0 / 255, blue: 255.0 / 255, alpha: 0.9)), location: 0), .init(color: Color.clear, location: 0.34)]), .linear(degrees: 125, stops: [.init(color: Color(uiColor: UIColor(red: 232.0 / 255, green: 232.0 / 255, blue: 229.0 / 255, alpha: 1)), location: 0), .init(color: Color(uiColor: UIColor(red: 245.0 / 255, green: 245.0 / 255, blue: 242.0 / 255, alpha: 1)), location: 0.62), .init(color: Color(uiColor: UIColor(red: 255.0 / 255, green: 255.0 / 255, blue: 255.0 / 255, alpha: 1)), location: 1)])]
        }
    }
    static let projectGlowSize: CGFloat = 160
    static let projectGlowRight: CGFloat = -65
    static let projectGlowTop: CGFloat = -70
    static let projectGlowBlur: CGFloat = 16
    static let projectGlowOpacity: CGFloat = 0.55
    static func projectGlow(_ accent: String?) -> Color {
        switch accent {
        case "green":
            return Color(uiColor: UIColor { traits in
                traits.userInterfaceStyle == .dark ? UIColor(red: 98.0 / 255, green: 213.0 / 255, blue: 155.0 / 255, alpha: 0.14) : UIColor(red: 26.0 / 255, green: 151.0 / 255, blue: 91.0 / 255, alpha: 0.1)
            })
        case "blue":
            return Color(uiColor: UIColor { traits in
                traits.userInterfaceStyle == .dark ? UIColor(red: 108.0 / 255, green: 167.0 / 255, blue: 255.0 / 255, alpha: 0.14) : UIColor(red: 56.0 / 255, green: 114.0 / 255, blue: 205.0 / 255, alpha: 0.1)
            })
        case "amber":
            return Color(uiColor: UIColor { traits in
                traits.userInterfaceStyle == .dark ? UIColor(red: 231.0 / 255, green: 183.0 / 255, blue: 100.0 / 255, alpha: 0.14) : UIColor(red: 179.0 / 255, green: 116.0 / 255, blue: 18.0 / 255, alpha: 0.1)
            })
        case "pink":
            return Color(uiColor: UIColor { traits in
                traits.userInterfaceStyle == .dark ? UIColor(red: 239.0 / 255, green: 138.0 / 255, blue: 184.0 / 255, alpha: 0.14) : UIColor(red: 239.0 / 255, green: 138.0 / 255, blue: 184.0 / 255, alpha: 0.14)
            })
        case "cyan":
            return Color(uiColor: UIColor { traits in
                traits.userInterfaceStyle == .dark ? UIColor(red: 88.0 / 255, green: 207.0 / 255, blue: 218.0 / 255, alpha: 0.14) : UIColor(red: 88.0 / 255, green: 207.0 / 255, blue: 218.0 / 255, alpha: 0.14)
            })
        default:
            return Color(uiColor: UIColor { traits in
                traits.userInterfaceStyle == .dark ? UIColor(red: 139.0 / 255, green: 120.0 / 255, blue: 255.0 / 255, alpha: 0.15) : UIColor(red: 111.0 / 255, green: 86.0 / 255, blue: 229.0 / 255, alpha: 0.1)
            })
        }
    }
    // Library palette only; no invented people or avatars are inserted into project cards.
    static func avatarLayers(_ accent: String, scheme: ColorScheme) -> [DLSGradientLayer] {
        switch accent {
        case "blue":
            if scheme == .dark { return [.linear(degrees: 145, stops: [.init(color: Color(uiColor: UIColor(red: 50.0 / 255, green: 95.0 / 255, blue: 152.0 / 255, alpha: 1)), location: 0.0), .init(color: Color(uiColor: UIColor(red: 22.0 / 255, green: 34.0 / 255, blue: 51.0 / 255, alpha: 1)), location: 1.0)])] }
            return [.linear(degrees: 145, stops: [.init(color: Color(uiColor: UIColor(red: 231.0 / 255, green: 242.0 / 255, blue: 252.0 / 255, alpha: 1)), location: 0.0), .init(color: Color(uiColor: UIColor(red: 211.0 / 255, green: 231.0 / 255, blue: 248.0 / 255, alpha: 1)), location: 1.0)])]
        case "green":
            if scheme == .dark { return [.linear(degrees: 145, stops: [.init(color: Color(uiColor: UIColor(red: 43.0 / 255, green: 116.0 / 255, blue: 88.0 / 255, alpha: 1)), location: 0.0), .init(color: Color(uiColor: UIColor(red: 21.0 / 255, green: 43.0 / 255, blue: 34.0 / 255, alpha: 1)), location: 1.0)])] }
            return [.linear(degrees: 145, stops: [.init(color: Color(uiColor: UIColor(red: 229.0 / 255, green: 244.0 / 255, blue: 237.0 / 255, alpha: 1)), location: 0.0), .init(color: Color(uiColor: UIColor(red: 206.0 / 255, green: 232.0 / 255, blue: 219.0 / 255, alpha: 1)), location: 1.0)])]
        case "amber":
            if scheme == .dark { return [.linear(degrees: 145, stops: [.init(color: Color(uiColor: UIColor(red: 128.0 / 255, green: 98.0 / 255, blue: 58.0 / 255, alpha: 1)), location: 0.0), .init(color: Color(uiColor: UIColor(red: 45.0 / 255, green: 36.0 / 255, blue: 24.0 / 255, alpha: 1)), location: 1.0)])] }
            return [.linear(degrees: 145, stops: [.init(color: Color(uiColor: UIColor(red: 247.0 / 255, green: 239.0 / 255, blue: 227.0 / 255, alpha: 1)), location: 0.0), .init(color: Color(uiColor: UIColor(red: 234.0 / 255, green: 219.0 / 255, blue: 196.0 / 255, alpha: 1)), location: 1.0)])]
        case "pink":
            if scheme == .dark { return [.linear(degrees: 145, stops: [.init(color: Color(uiColor: UIColor(red: 126.0 / 255, green: 63.0 / 255, blue: 99.0 / 255, alpha: 1)), location: 0.0), .init(color: Color(uiColor: UIColor(red: 44.0 / 255, green: 25.0 / 255, blue: 36.0 / 255, alpha: 1)), location: 1.0)])] }
            return [.linear(degrees: 145, stops: [.init(color: Color(uiColor: UIColor(red: 250.0 / 255, green: 234.0 / 255, blue: 242.0 / 255, alpha: 1)), location: 0.0), .init(color: Color(uiColor: UIColor(red: 241.0 / 255, green: 212.0 / 255, blue: 227.0 / 255, alpha: 1)), location: 1.0)])]
        case "cyan":
            if scheme == .dark { return [.linear(degrees: 145, stops: [.init(color: Color(uiColor: UIColor(red: 47.0 / 255, green: 111.0 / 255, blue: 118.0 / 255, alpha: 1)), location: 0.0), .init(color: Color(uiColor: UIColor(red: 20.0 / 255, green: 43.0 / 255, blue: 47.0 / 255, alpha: 1)), location: 1.0)])] }
            return [.linear(degrees: 145, stops: [.init(color: Color(uiColor: UIColor(red: 228.0 / 255, green: 244.0 / 255, blue: 245.0 / 255, alpha: 1)), location: 0.0), .init(color: Color(uiColor: UIColor(red: 204.0 / 255, green: 232.0 / 255, blue: 235.0 / 255, alpha: 1)), location: 1.0)])]
        default:
            if scheme == .dark { return [.linear(degrees: 145, stops: [.init(color: Color(uiColor: UIColor(red: 85.0 / 255, green: 74.0 / 255, blue: 145.0 / 255, alpha: 1)), location: 0.0), .init(color: Color(uiColor: UIColor(red: 32.0 / 255, green: 29.0 / 255, blue: 49.0 / 255, alpha: 1)), location: 1.0)])] }
            return [.linear(degrees: 145, stops: [.init(color: Color(uiColor: UIColor(red: 238.0 / 255, green: 234.0 / 255, blue: 253.0 / 255, alpha: 1)), location: 0.0), .init(color: Color(uiColor: UIColor(red: 221.0 / 255, green: 214.0 / 255, blue: 247.0 / 255, alpha: 1)), location: 1.0)])]
        }
    }
    static let accountTitle = Font.custom("Georgia", size: 22, relativeTo: .title2)
    static let accountAvatarBorder = Color(uiColor: UIColor { traits in
        traits.userInterfaceStyle == .dark ? UIColor(red: 255.0 / 255, green: 255.0 / 255, blue: 255.0 / 255, alpha: 0.14) : UIColor(red: 24.0 / 255, green: 24.0 / 255, blue: 27.0 / 255, alpha: 0.06)
    })
    static func accountAvatarInk(_ accent: String?) -> Color {
        let light: UIColor
        switch accent {
        case "blue": light = UIColor(red: 40.0 / 255, green: 88.0 / 255, blue: 132.0 / 255, alpha: 1)
        case "green": light = UIColor(red: 39.0 / 255, green: 100.0 / 255, blue: 78.0 / 255, alpha: 1)
        case "amber": light = UIColor(red: 114.0 / 255, green: 84.0 / 255, blue: 49.0 / 255, alpha: 1)
        case "pink": light = UIColor(red: 123.0 / 255, green: 62.0 / 255, blue: 96.0 / 255, alpha: 1)
        case "cyan": light = UIColor(red: 42.0 / 255, green: 98.0 / 255, blue: 106.0 / 255, alpha: 1)
        default: light = UIColor(red: 89.0 / 255, green: 74.0 / 255, blue: 145.0 / 255, alpha: 1)
        }
        return Color(uiColor: UIColor { traits in
            traits.userInterfaceStyle == .dark ? UIColor(red: 236.0 / 255, green: 232.0 / 255, blue: 245.0 / 255, alpha: 1) : light
        })
    }
    static let authTitle = Font.custom("Georgia", size: 30, relativeTo: .largeTitle)
    static let radiusButton: CGFloat = 9
    static let radiusControl: CGFloat = 10
    static let radiusCard: CGFloat = 14
    static let radiusAuthCard: CGFloat = 18
    static let radiusMobileCard: CGFloat = 20
    static let radiusPanel: CGFloat = 20
    static func projectAccent(_ name: String?) -> Color {
        switch name {
        case "green": return green
        case "blue": return blue
        case "amber": return amber
        case "pink": return pink
        case "cyan": return cyan
        default: return violet
        }
    }
}
